CREATE TYPE "reservation_status" AS ENUM (
  'PENDING',
  'CONFIRMED',
  'CANCELLED',
  'COMPLETED'
);

CREATE TYPE "payment_status" AS ENUM (
  'PENDING',
  'ACCEPTED',
  'DECLINED',
  'REFUNDED',
  'CANCELLED'
);

CREATE TYPE "conversation_status" AS ENUM (
  'OPEN',
  'WAITING',
  'ACTIVE',
  'PENDING_RESPONSE',
  'CLOSED'
);

CREATE TYPE "sender_type" AS ENUM (
  'USER',
  'SUPPORT_AGENT'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "email_verified" BOOLEAN NOT NULL DEFAULT false,
  "password" VARCHAR(255),
  "first_name" VARCHAR(100) NOT NULL,
  "last_name" VARCHAR(100) NOT NULL,
  "date_of_birth" DATE NOT NULL,
  "address" VARCHAR(255) NOT NULL,
  "language" VARCHAR(10) NOT NULL DEFAULT 'en',
  "auth_provider" VARCHAR(50),
  "external_auth_id" VARCHAR(255),
  "terms_accepted_at" TIMESTAMPTZ NOT NULL,
  "privacy_accepted_at" TIMESTAMPTZ NOT NULL,
  "stripe_customer_id" VARCHAR(255),
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "support_access" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "driver_licenses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" BIGINT UNIQUE NOT NULL,
  "number" VARCHAR(100) NOT NULL,
  "country" VARCHAR(100) NOT NULL,
  "expiry_date" DATE NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "support_conversations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" BIGINT NOT NULL,
  "chat_session_id" UUID NULL,
  "subject" VARCHAR(255) NOT NULL,
  "status" conversation_status NOT NULL DEFAULT 'OPEN',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "support_messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "conversation_id" BIGINT NOT NULL,
  "content" TEXT NOT NULL,
  "sent_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "sender_type" sender_type NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "agencies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "city" VARCHAR(100) NOT NULL,
  "country" VARCHAR(100) NOT NULL,
  "address" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "vehicle_categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "acriss_code" VARCHAR(10) UNIQUE NOT NULL,
  "label" VARCHAR(100) NOT NULL,
  "description" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "offers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "agency_id" BIGINT NOT NULL,
  "vehicle_category_id" BIGINT NOT NULL,
  "start_date" TIMESTAMPTZ NOT NULL,
  "end_date" TIMESTAMPTZ NOT NULL,
  "rate" DECIMAL(10,2) NOT NULL,
  "departure_city" VARCHAR(100) NOT NULL,
  "return_city" VARCHAR(100) NOT NULL,
  "cancellation_policy" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "reservations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" BIGINT NOT NULL,
  "offer_id" BIGINT NOT NULL,
  "reference" VARCHAR(100) UNIQUE NOT NULL,
  "total_price" DECIMAL(10,2) NOT NULL,
  "status" reservation_status NOT NULL DEFAULT 'PENDING',
  "refund_amount" DECIMAL(10,2) NULL,
  "invoice_reference" VARCHAR(255) NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "reservation_id" BIGINT UNIQUE NOT NULL,
  "stripe_payment_id" VARCHAR(255) NULL,
  "amount" DECIMAL(10,2) NOT NULL,
  "status" payment_status NOT NULL DEFAULT 'PENDING',
  "paid_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

ALTER TABLE "driver_licenses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE; 

ALTER TABLE "support_conversations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "support_messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "support_conversations" ("id") ON DELETE CASCADE;

ALTER TABLE "offers" ADD FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") ON DELETE RESTRICT;

ALTER TABLE "offers" ADD FOREIGN KEY ("vehicle_category_id") REFERENCES "vehicle_categories" ("id") ON DELETE RESTRICT;

ALTER TABLE "reservations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE RESTRICT;

ALTER TABLE "reservations" ADD FOREIGN KEY ("offer_id") REFERENCES "offers" ("id") ON DELETE RESTRICT;

ALTER TABLE "payments" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("id") ON DELETE CASCADE;